# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailorder_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailorder',
            name='letter',
            field=tinymce.models.HTMLField(),
        ),
    ]
