# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170526_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailorder',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
