# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mailorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailorder',
            name='usps_confirmation_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
