# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mailorder_usps_confirmation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailorder',
            name='sender_country',
        ),
    ]
