# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_mailorder_sender_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailorder',
            name='recipient_country',
        ),
    ]
