# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_mailorder_recipient_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailorder',
            name='pdf_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mailorder',
            name='letter',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
