# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_unit', models.CharField(max_length=200)),
                ('sender_street', models.CharField(max_length=200)),
                ('sender_state', models.CharField(max_length=20)),
                ('sender_zip', models.CharField(max_length=20)),
                ('recipiant_name', models.CharField(max_length=200)),
                ('recipiant_unit', models.CharField(max_length=200)),
                ('recipiant_street', models.CharField(max_length=200)),
                ('recipiant_state', models.CharField(max_length=20)),
                ('recipiant_zip', models.CharField(max_length=20)),
                ('payment_received', models.BooleanField()),
                ('printed', models.BooleanField()),
                ('delivered_to_post_office', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
