# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipiant_name',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipiant_state',
            new_name='recipient_state',
        ),
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipiant_street',
            new_name='recipient_street',
        ),
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipiant_unit',
            new_name='recipient_unit',
        ),
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipiant_zip',
            new_name='recipient_zip',
        ),
    ]
