# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170523_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailorder',
            old_name='recipient_street',
            new_name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='mailorder',
            name='recipient_zip',
        ),
        migrations.RemoveField(
            model_name='mailorder',
            name='sender_street',
        ),
        migrations.RemoveField(
            model_name='mailorder',
            name='sender_zip',
        ),
        migrations.AddField(
            model_name='mailorder',
            name='recipient_locality',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='recipient_postal_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='recipient_route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='recipient_state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='recipient_street_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_locality',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_postal_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailorder',
            name='sender_street_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
