# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170523_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailorder',
            name='letter',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
